### ISSUE TITLE
After /spawn player can't move

### ISSUE THREAD

**Issue by amadin** [GunshipPenguin/serveressentials#1]
If player sitting or lies and use /spawn - he will continue sitting or lies after teleporting to spawn and don't move.

**Comment by GunshipPenguin** [comment]
You're being a bit vague here. What do you mean by "sitting or lies"? How exactly do I replicate this problem? I played around with the /spawn command and it seems to be working as expected.

**Comment by amadin** [comment]
You must sit on chair (from xdecor mod for example) and use /spawn.

**Comment by GunshipPenguin** [comment]
The problem you're experiencing seems to be from a call to player:set_physics_override() on a sitting player in the xdecor mod [here](https://github.com/kilbith/xdecor/blob/b88867b6d30e7231cb0c79701d42c6dd0a3d7174/sitting.lua#L16). 

set_physics_override(0,0,0) is called to ensure that sitting players do not move. When a player right clicks the chair to stop sitting, set_physics_override(1,1,1) is called to make it so that the player can walk again. When the player invokes /spawn however, set_physics_override(1,1,1) is not called, and the player is no longer in the chair, so he cannot right click it to allow himself to move again.

This can be fixed by adding the following code [here](https://github.com/GunshipPenguin/serveressentials/blob/master/init.lua#L36)

```
minetest.get_player_by_name(playerName):set_physics_override(1, 1, 1)
```

I'm not going to make this change this in this repository though, as I can see a call to set_physics_override causing problems with other mods that use it.

**Comment by amadin** [comment]
You must add changing first person view also.
